# Generated by Django 4.2.7 on 2023-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
    ]
